### ISSUE TITLE
Blockquotes?

### ISSUE THREAD

**Issue by hrdlnk** [talonbragg/markthat#1]
`markthat.markthat('> Hello world, I *should* be a blockquote...');`

returns

`> Hello world, I <em>should</em> be a blockquote...`

instead of

`<blockquote>Hello world, I <em>should</em> be a blockquote...</blockquote>`

**Comment by talonbragg** [comment]
Sorry that I am getting to this so late, I was working on other projects. I will add this, thank you for the recommendation.

**Comment by talonbragg** [comment]
I have added this feature and am going to close this issue now.
